platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

def common_pods
    pod 'SnapKit', '~> 3.0.2'
end

target 'SwiftLoadingHUD' do

  common_pods

  target 'SwiftLoadingHUDTests' do
    inherit! :search_paths
  end

  target 'SwiftLoadingHUDUITests' do
    inherit! :search_paths
  end

end
